[workspace]

resolver = "2"

members = [
    "number",
    "parser",
    "powdr_cli",
    "executor",
    "riscv",
    "parser_util",
    "pil_analyzer",
    "compiler",
    "pilopt",
    "asm_to_pil",
    "backend",
    "bberg",
    "bberg_pil_cli",
    "ast",
    "analysis",
    "linker",
    "asm_utils",
    "airgen",
    "type_check",
    "riscv_executor",
]


[profile.pr-tests]
inherits = "dev"
opt-level = 3
debug = "line-tables-only"
debug-assertions = true
overflow-checks = true
panic = 'unwind'
incremental = true         # This is true because target is cached
codegen-units = 256
