[package]
name = "pil_analyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
number = { path = "../number" }
parser_util = { path = "../parser_util" }
parser = { path = "../parser" }
ast = { path = "../ast" }
itertools = "^0.10"

[dev-dependencies]
test-log = "0.2.12"
env_logger = "0.10.0"
pretty_assertions = "1.3.0"
