[package]
name = "linker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ast = { path = "../ast" }
number = { path = "../number" }
analysis = { path = "../analysis" }
pretty_assertions = "1.3.0"

[dev-dependencies]
parser = { path = "../parser" }
airgen = { path = "../airgen" }
importer = { path = "../importer" }
